#!/bin/bash
set -euo pipefail

# Check if 2 arguments were given
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <image-name> <dockerfile>"
    exit 1
fi

IMAGE_NAME=$1
DOCKERFILE=$2
# We use the catalog in which the script is as context
CONTEXT_DIR=$(dirname "$0")

echo ">>> Building Docker image '$IMAGE_NAME' from '$DOCKERFILE'..."

# Launching build with correct parameters
docker build -t "$IMAGE_NAME" -f "$CONTEXT_DIR/$DOCKERFILE" "$CONTEXT_DIR"

echo ">>> Docker image '$IMAGE_NAME' built successfully."
